{
 "title": "DRON",
 "description": "Datos meteorológicos del dron",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Humidity, Temperature and Gas Resistance",
   "type": "timeseries",
   "description": "Humedad(%)\nTemperatura(°C)\nGas resistance(kΩ)",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"humedad\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"gas_resistance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Grados Celcius",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"temperatura\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Humedad relativa",
   "gridPos": { "h": 14, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"humedad\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": {
    "content": "<img src=\"https://scontent.fgdl3-1.fna.fbcdn.net/v/t39.30808-6/481029678_1214667017328412_2072581575751997266_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=127cfc&_nc_ohc=Ogl8goeuKfYQ7kNvwGUTywv&_nc_oc=Adlgr2wez-aGbf6scjZMvQjxgwxM00pBDjA9NF18noxTgpsEpJVxxPa8w8R37rZI0w89DaXCpYsotdWYIcy0PdBD&_nc_zt=23&_nc_ht=scontent.fgdl3-1.fna&_nc_gid=-vB5EPZLOMkHb_4uQdqYkA&oh=00_AfFyeLiYs7ri1OIMrxg_YRD_NaoyAGF3pKMLJFsj3OSfGg&oe=6815F528\" width=\"600\">\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 21, "w": 3, "x": 21, "y": 8 },
   "options": {
    "content": "<div style=\"text-align: center; font-size: 36px; font-weight: bold; color: #FFFFFF;\">\n  Dron Meteorológico Autónomo \n</div>\n\n<br>\n\n<div style=\"text-align: justify; font-size: 15px; color: #FFFFFF;\">\n  Este proyecto corresponde a un dron Meteorológico inteligente completamente funcional, equipado con sensores capaces de recolectar datos ambientales en tiempo real durante el vuelo.\n  El sistema integra una estación base de monitoreo que permite visualizar, almacenar y analizar los datos transmitidos desde el dron de manera remota.\n</div>\n\n<br>\n\n<div style=\"font-size: 18px; color: #FFFFFF;\"><b>Variables medidas en tiempo real:</b></div>\n<ul style=\"font-size: 15px; color: #FFFFFF;\">\n  <li> Temperatura ambiente</li>\n  <li> Humedad relativa</li>\n  <li> Altitud estimada</li>\n  <li> Presión atmosférica</li>\n  <li> Índice de calidad del aire (gas)</li>\n</ul>\n\n<br>\n"
   }
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"altitud\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "gauge",
   "description": "metros",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"altitud\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "gauge",
   "description": "kilo ohms",
   "gridPos": { "h": 15, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kohm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"gas_resistance\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": " Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"presion\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": " Pressure",
   "type": "gauge",
   "description": "hectoPascal",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"DanielBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"bme688\")\r\n  |> filter(fn: (r) => r._field == \"presion\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}